export const columns = [
   {name: 'NAME', uid: 'name'},
   {name: 'DETAILS', uid: 'details'},
   {name: 'STATUS', uid: 'status'},
   {name: 'ACTIONS', uid: 'actions'},
   {name: 'CONTACT' ,uid: 'contact'}
];
export const users = [
   {
     id: 1,
     name: "Aarya",
     grade: "3",
     section: "A",
     status: "active",
     age: "10",
     avatar: "/assets/aarya.jpeg",
     email: "aarya@example.com",
     phone: "9876543210",
   },
   {
     id: 2,
     name: "Addhya",
     grade: "3",
     section: "A",
     status: "active",
     age: "10",
     avatar: "assets/riyea.jpeg",
     email: "addhya@example.com",
     phone: "9876543211",
   },
   {
     id: 3,
     name: "Amrita",
     grade: "3",
     section: "A",
     status: "active",
     age: "10",
     avatar: "/assets/amrita.jpeg",
     email: "amrita@example.com",
     phone: "9876543212",
   },
   {
     id: 4,
     name: "Ananay",
     grade: "3",
     section: "A",
     status: "active",
     age: "10",
     avatar: "/assets/ananay.jpeg",
     email: "ananay@example.com",
     phone: "9876543213",
   },
   {
     id: 5,
     name: "Atif",
     grade: "3",
     section: "A",
     status: "active",
     age: "9",
     avatar: "/assets/atif.jpeg",
     email: "atif@example.com",
     phone: "9876543214",
   },
   {
     id: 6,
     name: "Bhavya",
     grade: "3",
     section: "A",
     status: "active",
     age: "9",
     avatar: "/assets/bhavya.jpeg",
     email: "bhavya@example.com",
     phone: "9876543215",
   },
   {
     id: 7,
     name: "Devansh",
     grade: "3",
     section: "A",
     status: "paused",
     age: "10",
     avatar: "/assets/devansh.jpeg",
     email: "devansh@example.com",
     phone: "9876543216",
   },
   {
     id: 8,
     name: "Divyansh",
     grade: "3",
     section: "A",
     status: "active",
     age: "9",
     avatar: "/assets/divyansh.jpeg",
     email: "divyansh@example.com",
     phone: "9876543217",
   },
   {
     id: 9,
     name: "Mihika",
     grade: "3",
     section: "A",
     status: "active",
     age: "8",
     avatar: "/assets/mihika.jpeg",
     email: "mihika@example.com",
     phone: "9876543218",
   },
   {
     id: 10,
     name: "Revansh",
     grade: "3",
     section: "A",
     status: "active",
     age: "8",
     avatar: "/assets/revansh.jpeg",
     email: "revansh@example.com",
     phone: "9876543219",
   },
   {
     id: 11,
     name: "Reza",
     grade: "3",
     section: "A",
     status: "active",
     age: "9",
     avatar: "/assets/reza.jpeg",
     email: "reza@example.com",
     phone: "9876543220",
   },
   {
     id: 12,
     name: "Rieya",
     grade: "3",
     section: "A",
     status: "active",
     age: "8",
     avatar: "/assets/rieya.jpeg",
     email: "rieya@example.com",
     phone: "9876543221",
   },
   {
     id: 13,
     name: "Rinkly",
     grade: "3",
     section: "A",
     status: "active",
     age: "10",
     avatar: "/assets/rinkly.jpeg",
     email: "rinkly@example.com",
     phone: "9876543222",
   },
   {
     id: 14,
     name: "Rivansh",
     grade: "3",
     section: "A",
     status: "active",
     age: "10",
     avatar: "/assets/rivansh.jpeg",
     email: "rivansh@example.com",
     phone: "9876543223",
   },
   {
     id: 15,
     name: "Riya",
     grade: "3",
     section: "A",
     status: "active",
     age: "9",
     avatar: "/assets/riya.jpeg",
     email: "riya@example.com",
     phone: "9876543224",
   },
   {
     id: 16,
     name: "Rohit",
     grade: "3",
     section: "A",
     status: "active",
     age: "8",
     avatar: "/assets/images/rohit.jpeg",
     email: "rohit@example.com",
     phone: "9876543225",
   },
 ];
 


// export const columns = [
//    { name: 'NAME', uid: 'name' },
//    { name: 'AGE', uid: 'age' },
//    { name: 'GRADE', uid: 'grade' },
//    { name: 'SECTION', uid: 'section' },
//    { name: 'STATUS', uid: 'status' },
//    { name: 'ACTIONS', uid: 'actions' },
// ];

// export const students = [
//    { id: 1, name: 'Aarya', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/aarya.jpeg', email: 'aarya@example.com' },
//    { id: 2, name: 'Addhya', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/addhya.jpeg', email: 'addhya@example.com' },
//    { id: 3, name: 'Amrita', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/amrita.jpeg', email: 'amrita@example.com' },
//    { id: 4, name: 'Ananay', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/ananay.jpeg', email: 'ananay@example.com' },
//    { id: 5, name: 'Atif', grade: '4', section: 'A', status: 'active', age: '9', avatar: 'assets/atif.jpeg', email: 'atif@example.com' },
//    { id: 6, name: 'Bhavya', grade: '4', section: 'A', status: 'active', age: '9', avatar: 'assets/bhavya.jpeg', email: 'bhavya@example.com' },
//    { id: 7, name: 'Devansh', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/devansh.jpeg', email: 'devansh@example.com' },
//    { id: 8, name: 'Divyansh', grade: '4', section: 'A', status: 'active', age: '9', avatar: 'assets/divyansh.jpeg', email: 'divyansh@example.com' },
//    { id: 9, name: 'Mihika', grade: '3', section: 'A', status: 'active', age: '8', avatar: 'assets/mihika.jpeg', email: 'mihika@example.com' },
//    { id: 10, name: 'Revansh', grade: '3', section: 'A', status: 'active', age: '8', avatar: 'assets/revansh.jpeg', email: 'revansh@example.com' },
//    { id: 11, name: 'Reza', grade: '4', section: 'A', status: 'active', age: '9', avatar: 'assets/reza.jpeg', email: 'reza@example.com' },
//    { id: 12, name: 'Rieya', grade: '3', section: 'A', status: 'active', age: '8', avatar: 'assets/rieya.jpeg', email: 'rieya@example.com' },
//    { id: 13, name: 'Rinkly', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/rinkly.jpeg', email: 'rinkly@example.com' },
//    { id: 14, name: 'Rivansh', grade: '5', section: 'A', status: 'active', age: '10', avatar: 'assets/rivansh.jpeg', email: 'rivansh@example.com' },
//    { id: 15, name: 'Riya', grade: '4', section: 'A', status: 'active', age: '9', avatar: 'assets/riya.jpeg', email: 'riya@example.com' },
//    { id: 16, name: 'Ronit', grade: '3', section: 'A', status: 'active', age: '8', avatar: 'assets/images/rohit.jpeg', email: 'ronit@example.com' },
// ];
